## Inputs paths

sample_bam: /single-cell/input/1/possorted_genome_trimmed.bam
barcodes: /single-cell/input/1/barcodes_reduced.txt

reference: /single-cell/input/reference/genome.fasta
regions: /single-cell/input/reference/regions.txt
reference_MT: /single-cell/input/reference/MT.fasta
regions_MT: /single-cell/input/reference/MT_regions.txt

# for analysis
ref_exome: /single-cell/input/exome_96_remmapedto38.vcf.gz
ref_population: /single-cell/input/1000G/1000G_populations.txt
dirpath_1000G: /single-cell/input/1000G/

## Parameters for rules
cores: 40
# Snakefile
dp: 50
qual: 60
# threshold for iteration 1
thr_cell_1: 10
# threshold for iteration 2
thr_cell_2: 20

# rule for merging cells python
threshold_coverage: 10
threshold_coverage_pos: 5
threshold_base_calling: 90

# rule for for clustering Rscript
n_neighbors: 5
n_components: 3
# if clusters > 1 then nBclust is executed to predict number of clusters to use
clusters: 0

###########################
#### Snakefile_analysis
###########################

dirpath_analysis: output
dp_2: 50
qual_2: 60

# Yleaf parameters
read_depth: 1
quality: 20
base_calling: 90
positions_file: /single-cell/software/Yleaf/Position_files/WGS_hg38.txt

# STRUCTURE parameters
mainparams_file: /single-cell/input/structure/mainparams
extraparams_file: /single-cell/input/structure/extraparams
